### PR TITLE
Fixes #8849 - reorder postgres permissions to fix installing katello-dev...

### PR DESCRIPTION
**Pull request by dustints**
...el-installer with gutterball

### CODE REVIEW

**Comment by dustints** [comment]
abandoning as well...see https://github.com/Katello/puppet-katello/pull/55

**Comment by ehelms** [comment]
Could you use https://github.com/puppetlabs/puppetlabs-postgresql#order to achieve this?

**Comment by dustints** [comment]
@ehelms yup, but will need to update puppet_katello-devel instead of here since all
the default order is 150 and is lowest priority..and because I want to drop priority of this...need to increase priority of rules in katello-devel

**Comment by dustints** [comment]
updating order in github.com/Katello/puppet-katello_devel/pull/29

**Pull request closed without merging**
